version: '3.9'

services:
  mongo-albums:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_album_data:/data/db
    networks:
      - default

  mysql-genres:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_genre_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - default

  mysql-artists:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_artist_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - default

  mysql-songs:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_song_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - default

  genre-service:
    depends_on:
      - mysql-genres
    image: thomi2003/genre-service:latest
    ports:
      - 8080:8080
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-genres
      MYSQL_DB_PORT: 3306
    networks:
      - default

  artist-service:
    depends_on:
      - mysql-artists
    image: thomi2003/artist-service:latest
    ports:
      - 8081:8081
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-artists
      MYSQL_DB_PORT: 3306
    networks:
      - default

  song-service:
    depends_on:
      - mysql-songs
    image: thomi2003/song-service:latest
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-songs
      MYSQL_DB_PORT: 3306
    networks:
      - default

  album-service:
    depends_on:
      - mongo-albums
    image: thomi2003/album-service:latest
    ports:
      - 8083:8083
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-albums
    networks:
      - default

  api-gateway:
    depends_on:
      - genre-service
      - artist-service
      - song-service
      - album-service
    image: thomi2003/api-gateway:latest
    ports:
      - 8084:8084
    links:
      - genre-service
      - artist-service
      - song-service
      - album-service
    environment:
      GENRE_SERVICE_HOST: genre-service
      GENRE_SERVICE_PORT: 8080
      ARTIST_SERVICE_HOST: artist-service
      ARTIST_SERVICE_PORT: 8081
      SONG_SERVICE_HOST: song-service
      SONG_SERVICE_PORT: 8082
      ALBUM_SERVICE_HOST: album-service
      ALBUM_SERVICE_PORT: 8083
    networks:
      - default

      
networks:
  default:
    driver: bridge

volumes:
  mongodb_album_data:
  mysql_genre_data:
  mysql_artist_data:
  mysql_song_data:
