server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: artist-service
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/artists
            - Method=GET
          filters:
            - SetPath=/api/artists
        - id: genre-service-all
          uri: http://${GENRE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/genres
            - Method=GET
          filters:
            - SetPath=/api/genres
        - id: song-service-all
          uri: http://${SONG_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/songs
            - Method=GET
          filters:
            - SetPath=/api/songs
        - id: album-service
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - SetPath=/api/albums