apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-artists
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-artists
  template:
    metadata:
      labels:
        app: mysql-artists
    spec:
      containers:
        - name: mysql-artists
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "abc123"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-artists
  namespace: default
spec:
  selector:
    app: mysql-artists
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: artist-service
  template:
    metadata:
      labels:
        app: artist-service
    spec:
      containers:
        - name: artist-service
          image: thomi2003/artist-service:latest
          env:
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_HOST
              value: "mysql-artists"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "abc123"

---
apiVersion: v1
kind: Service
metadata:
  name: artist-service
  namespace: default
spec:
  selector:
    app: artist-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081