apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-genres
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-genres
  template:
    metadata:
      labels:
        app: mysql-genres
    spec:
      containers:
        - name: mysql-genres
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "abc123"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-genres
  namespace: default
spec:
  selector:
    app: mysql-genres
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: genre-service
  template:
    metadata:
      labels:
        app: genre-service
    spec:
      containers:
        - name: genre-service
          image: thomi2003/genre-service:latest
          env:
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_HOST
              value: "mysql-genres"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "abc123"

---
apiVersion: v1 
kind: Service
metadata:
  name: genre-service
  namespace: default
spec:
  selector:
    app: genre-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080