apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-songs
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-songs
  template:
    metadata:
      labels:
        app: mysql-songs
    spec:
      containers:
        - name: mysql-songs
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "abc123"
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-songs
  namespace: default
spec:
  selector:
    app: mysql-songs
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: thomi2003/song-service:latest
          env:
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_HOST
              value: "mysql-songs"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "abc123"

---
apiVersion: v1 
kind: Service
metadata:
  name: song-service
  namespace: default
spec:
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080